# Generated by Django 3.1.2 on 2020-11-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='krotki_opis',
            field=models.TextField(default='Krotki opis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='choroby',
            field=models.TextField(default='Choroby'),
        ),
        migrations.AlterField(
            model_name='post',
            name='nazwa',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='opis',
            field=models.TextField(default='Opis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='zastosowanie',
            field=models.TextField(default='Zastosowanie'),
        ),
    ]
