# Generated by Django 3.1.2 on 2020-11-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia_app', '0002_auto_20201124_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_apteczka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ziola', models.ManyToManyField(to='encyklopedia_app.Post')),
            ],
        ),
    ]
