# Generated by Django 3.1.2 on 2020-11-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia_app', '0003_post_apteczka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='krotki_opis',
        ),
    ]
