# Generated by Django 3.1.2 on 2020-11-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia_app', '0006_auto_20201130_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='members',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
