# Generated by Django 3.1.2 on 2020-12-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia_app', '0007_auto_20201130_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaZiol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ziola', models.ManyToManyField(to='encyklopedia_app.Post')),
            ],
        ),
    ]
