# Generated by Django 3.1.2 on 2020-12-01 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encyklopedia_app', '0008_listaziol'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaziol',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
